##数据源配置
spring:
  datasource:
    dynamic:
      primary: lims
      datasource:
        lims:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/lims
          username: postgres
          password: 123456
          druid:
            stat-view-servlet:
              login-username: blade
              login-password: 1qaz@WSX
        ams:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://192.168.0.151:5432/ams_input
          username: postgres
          password: 123456